/**
 * IdaaS exec secret provider 桥接层
 *
 * OpenClaw 的 exec secret provider 有一套标准协议（stdin JSON → stdout JSON），
 * 而 alibaba-cloud-idaas CLI 使用 CLI 参数格式。这个模块负责：
 * 1. 生成桥接脚本（idaas-exec-resolver.mjs），放到 {stateDir}/alicloud-idaas/ 供 exec provider 调用
 *
 * Provider 注册已移至 plan-builder.ts 通过 SecretsApplyPlan.providerUpserts 完成，
 * 不再需要 openclaw/plugin-sdk/config-runtime 依赖。
 *
 * Exec provider 协议：
 *   stdin:  { protocolVersion: 1, provider: "idaas", ids: string[] }
 *   stdout: { protocolVersion: 1, values: Record<string, string>, errors?: Record<string, {message: string}> }
 *
 * alibaba-cloud-idaas get-secret 协议：
 *   CLI:    agent get-secret --config <profile> --name <id>
 *   stdout: { "<name>": { success: bool, message: string, value?: { apiKeyContent?: { apiKey?: string } } } }
 */

import fs from "node:fs/promises";
import path from "node:path";
import { logInfo, logError } from "../logger.js";
import { IDAAS_PERSIST_DIR_NAME, resolveIdaasPersistDir } from "./idaas-config.js";

/** 桥接脚本文件名（plan-builder.ts 引用此常量构建 provider config） */
export const EXEC_RESOLVER_FILENAME = "idaas-exec-resolver.mjs";

/**
 * 桥接脚本模板
 *
 * 这是一个独立的 Node.js ESM 脚本，运行时不依赖插件的模块上下文。
 * 它从 stdin 读取 exec provider 请求，逐个调用 alibaba-cloud-idaas CLI 获取凭据，
 * 然后将结果转换为 exec provider 协议格式输出到 stdout。
 */
const EXEC_RESOLVER_SCRIPT = `#!/usr/bin/env node
/**
 * IdaaS exec secret provider resolver
 *
 * Bridges the OpenClaw exec secret provider protocol with the alibaba-cloud-idaas CLI.
 *
 * Protocol:
 *   stdin:  JSON { protocolVersion: 1, provider: "idaas", ids: string[] }
 *   stdout: JSON { protocolVersion: 1, values: Record<string, string>, errors?: Record<string, {message}> }
 *
 * Auto-generated by openclaw-security-assistant plugin. Do not edit manually.
 */
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLI_PATH = join(__dirname, "alibaba-cloud-idaas");
const PROFILE_PATH = join(__dirname, "alibaba-cloud-idaas.json");
const CLI_TIMEOUT_MS = 30000;

// Read all stdin
let input = "";
process.stdin.setEncoding("utf-8");
for await (const chunk of process.stdin) {
    input += chunk;
}

let request;
try {
    request = JSON.parse(input);
} catch {
    process.stdout.write(JSON.stringify({
        protocolVersion: 1,
        values: {},
        errors: { _: { message: "Invalid JSON input on stdin" } },
    }));
    process.exit(1);
}

const ids = Array.isArray(request.ids) ? request.ids : [];
const values = {};
const errors = {};

for (const id of ids) {
    try {
        const result = spawnSync(
            CLI_PATH,
            ["agent", "get-secret", "--config", PROFILE_PATH, "--name", String(id)],
            { encoding: "utf-8", timeout: CLI_TIMEOUT_MS, stdio: ["ignore", "pipe", "pipe"] },
        );

        if (result.error) {
            errors[id] = { message: result.error.message };
            continue;
        }
        if (result.status !== 0) {
            errors[id] = { message: result.stderr?.trim() || \`exit code \${result.status}\` };
            continue;
        }

        const stdout = (result.stdout || "").trim();
        if (!stdout) {
            errors[id] = { message: "empty CLI output" };
            continue;
        }

        let parsed;
        try {
            parsed = JSON.parse(stdout);
        } catch {
            errors[id] = { message: "invalid JSON response from CLI" };
            continue;
        }
        if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
            errors[id] = { message: "CLI returned non-object JSON" };
            continue;
        }
        const entries = Object.values(parsed);
        if (entries.length === 0) {
            errors[id] = { message: "empty response object" };
            continue;
        }

        const entry = entries[0];
        if (!entry.success) {
            errors[id] = { message: entry.message || "secret not found" };
            continue;
        }

        const apiKey = entry?.value?.apiKeyContent?.apiKey;
        if (!apiKey) {
            errors[id] = { message: "apiKey field not found in response" };
            continue;
        }

        values[id] = apiKey;
    } catch (e) {
        errors[id] = { message: String(e?.message || e) };
    }
}

const response = { protocolVersion: 1, values };
if (Object.keys(errors).length > 0) {
    response.errors = errors;
}
process.stdout.write(JSON.stringify(response));
`;

/**
 * 将桥接脚本写入 idaas 持久化目录，使其可被 exec secret provider 调用
 *
 * 写入路径：{stateDir}/alicloud-idaas/idaas-exec-resolver.mjs
 *
 * @param stateDir - OpenClaw state 目录（如 ~/.openclaw）
 * @returns 脚本的绝对路径
 */
export async function writeExecResolverScript(stateDir: string): Promise<string> {
    const idaasDir = resolveIdaasPersistDir(stateDir);
    const scriptPath = path.join(idaasDir, EXEC_RESOLVER_FILENAME);

    try {
        await fs.mkdir(idaasDir, { recursive: true });
        await fs.writeFile(scriptPath, EXEC_RESOLVER_SCRIPT, "utf-8");
        // 设置可执行权限（Unix 需要，Windows 上无实际效果但不报错）
        await fs.chmod(scriptPath, 0o755);

        logInfo("idaas_exec_resolver", "script_written", { path: scriptPath });
        return scriptPath;
    } catch (e: unknown) {
        const errorMsg = String(e instanceof Error ? e.message : e);
        logError("idaas_exec_resolver", "script_write_failed", { path: scriptPath, error: errorMsg });
        throw e;
    }
}
